### ISSUE TITLE
Random crash after a while of running

### ISSUE THREAD

**Issue by cnibbler** [alexa-pi/AlexaPi#227]
Hi,

I'm running alexapi interactively using a screen session so I can see what's happening if anything goes wrong and I've noticed that it crashes every so often. Never straight away and to be honest I don't always keep an eye on it so I haven't noticed any events to be the cause of the crash, I just see that bot LEDS are lit at the same time. When I check the screen session I just see this at the bottom of the screen:
2017-05-06 14:28:01 INFO: AVS token: Obtained successfully
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/AlexaPi/src/main.py", line 542, in trigger_process
    alexa_speech_recognizer(audio_stream)
  File "/opt/AlexaPi/src/main.py", line 347, in alexa_speech_recognizer
    resp = requests.post(url, headers=headers, data=data)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 454, in send
    r = low_conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 408, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

Just thought that you might like to know :)

Also, the auto-restart on crash doesn't appear to work when this occurs.

While I'm here, I might as well be a bit cheeky, any idea on when the new Alexa API will be implemented or if it can be done? ;)

Thanks

**Comment by EmerickH** [comment]
@cnibbler That's a bug but why don't you start AlexaPi as service?
I've no idea if someone is working on implementing new Alexa API but I think it's very difficult!

Emerick
