### ISSUE TITLE
Won't Install. Get Traceback Errors

### ISSUE THREAD

**Issue by mistergrumpy** [alexa-pi/AlexaPi#234]
Hello, 
Trying to install onto RPI 3 with Python 2.7 following this guide [http://lifehacker.com/the-simplest-way-to-build-a-raspberry-pi-powered-amazon-1794218212](url) but getting traceback errors when I try to install it. Any ideas?

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/easy_install.py", line 4, in <module>
    from setuptools.command.easy_install import main
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 9, in <module>
    from pyparsing import stringStart, stringEnd, originalTextFor, ParseException
ImportError: No module named pyparsing
`

**Comment by mistergrumpy** [comment]
So I've installed pyparsing, then had another traceback error and installed appdirs then got another traceback error:Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/easy_install.py", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 2280, in main
    **kw
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 321, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 389, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (appdirs 1.3.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('appdirs>=1.4.0'))

**Comment by mistergrumpy** [comment]
Solved. I had to reinstall pip, then appdirs, then update it then run again. Something I thought I had done numerous times but there you go!
