### ISSUE TITLE
audio issues: following wiki, permissions denied

### ISSUE THREAD

**Issue by jimmwaller** [alexa-pi/AlexaPi#244]
I am running the latest full version of Jessie on a rpi3

**Description of problem:**
I get errors when I run AlexaPi.  I think they have to do with pulse audio, and I saw the wiki entry about running it in systemwide mode.  However, when I follow the steps to either run it in systemwide mode OR disable it, I get the same "permission denied".

I even followed the "if you are having trouble with permissions..." bit, and I can't change owners.

the error I get on the terminal is "Process: 13255 ExecStart=/usr/bin/python /opt/AlexaPi/src/main.py --daemon (code=exited, status=1/FAILURE)"

any help would be appreciated.  thanks!

**Comment by EmerickH** [comment]
Hello,
Try starting AlexaPi with:
```
sudo /opt/AlexaPi/src/main.py -d
```
and copy/paste the output here.
And also copy/paste your `/etc/opt/AlexaPi/config.yaml` file

Emerick

**Comment by DigZworld** [comment]
Please help
Running latest version on rpi0w

pi@raspberrypi:~ $ sudo /opt/AlexaPi/src/main.py -d
2017-06-03 16:16:04 CRITICAL: Your input_device 'pluse' is invalid. Use one of the following:
null
pulse
default:CARD=Device
sysdefault:CARD=Device
front:CARD=Device,DEV=0
surround21:CARD=Device,DEV=0
surround40:CARD=Device,DEV=0
surround41:CARD=Device,DEV=0
surround50:CARD=Device,DEV=0
surround51:CARD=Device,DEV=0
surround71:CARD=Device,DEV=0
iec958:CARD=Device,DEV=0
dmix:CARD=Device,DEV=0
dsnoop:CARD=Device,DEV=0
hw:CARD=Device,DEV=0
plughw:CARD=Device,DEV=0

pi@raspberrypi:~ $ sudo nano etc/opt/AlexaPi/config.yaml
pi@raspberrypi:~ $ etc/opt/AlexaPi/config.yaml
bash: etc/opt/AlexaPi/config.yaml: No such file or directory
pi@raspberrypi:~ $

**Comment by maso27** [comment]
I see two things to fix, so I'll just pop in here and say:
1.) you have set the input_device to "pluse".  You probably meant to try "pulse".
2.) you need a "/" in front of etc/opt/AlexaPi/config.yaml, so it's `sudo nano /etc/opt/AlexaPi/config.yaml`.

**Comment by DigZworld** [comment]
Thanks Maso27.  I made the changes and now have an interesting mess.  Audio was unintelligible and choppy.  now it looks like the system crashed

pi@raspberrypi:~ $ sudo nano /etc/opt/AlexaPi/config.yaml
pi@raspberrypi:~ $ sudo systemctl start AlexaPi.service -l
pi@raspberrypi:~ $ sudo systemctl status AlexaPi.service -l
● AlexaPi.service - Alexa client for all your devices
   Loaded: loaded (/usr/lib/systemd/system/AlexaPi.service; enabled)
   Active: active (running) since Sat 2017-06-03 16:31:10 UTC; 7s ago
     Docs: https://github.com/alexa-pi/AlexaPi/wiki
 Main PID: 1414 (python)
   CGroup: /system.slice/AlexaPi.service
           └─1414 /usr/bin/python /opt/AlexaPi/src/main.py --daemon

Jun 03 16:31:10 raspberrypi systemd[1]: Started Alexa client for all your devices.
pi@raspberrypi:~ $ sudo systemctl status AlexaPi.service -l
● AlexaPi.service - Alexa client for all your devices
   Loaded: loaded (/usr/lib/systemd/system/AlexaPi.service; enabled)
   Active: active (running) since Sat 2017-06-03 16:31:10 UTC; 39s ago
     Docs: https://github.com/alexa-pi/AlexaPi/wiki
 Main PID: 1414 (python)
   CGroup: /system.slice/AlexaPi.service
           ├─1414 /usr/bin/python /opt/AlexaPi/src/main.py --daemon
           └─1438 /usr/bin/pulseaudio --start --log-target=syslog

Jun 03 16:31:43 raspberrypi python[1414]: [b3d0a338] alsa audio output error: cannot estimate delay: Input/output error
Jun 03 16:31:43 raspberrypi python[1414]: [b3d0a338] alsa audio output error: cannot estimate delay: Input/output error
Jun 03 16:31:43 raspberrypi python[1414]: [b3d0a338] alsa audio output error: cannot estimate delay: Input/output error
Jun 03 16:31:43 raspberrypi python[1414]: [b3d0a338] alsa audio output error: cannot estimate delay: Input/output error
Jun 03 16:31:43 raspberrypi python[1414]: [b3d0a338] alsa audio output error: cannot estimate delay: Input/output error
Jun 03 16:31:43 raspberrypi python[1414]: [b3d0a338] alsa audio output error: cannot estimate delay: Input/output error
Jun 03 16:31:44 raspberrypi python[1414]: [b3d0a338] alsa audio output error: cannot estimate delay: Input/output error
Jun 03 16:31:44 raspberrypi python[1414]: [b3d0a338] alsa audio output error: cannot estimate delay: Input/output error
Jun 03 16:31:44 raspberrypi python[1414]: [b3d0a338] alsa audio output error: cannot estimate delay: Input/output error
Jun 03 16:31:44 raspberrypi python[1414]: [b3d0a338] alsa audio output error: cannot estimate delay: Input/output error

**Comment by DigZworld** [comment]
pi@raspberrypi:~ $ sudo /opt/AlexaPi/src/main.py -d
INFO: pocketsphinx.c(152): Parsed model-specific feature parameters from /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/feat.params
Current configuration:
[NAME]			[DEFLT]		[VALUE]
-agc			none		none
-agcthresh		2.0		2.000000e+00
-allphone				
-allphone_ci		no		no
-alpha			0.97		9.700000e-01
-ascale			20.0		2.000000e+01
-aw			1		1
-backtrace		no		no
-beam			1e-48		1.000000e-48
-bestpath		yes		yes
-bestpathlw		9.5		9.500000e+00
-ceplen			13		13
-cmn			live		batch
-cmninit		40,3,-1		41.00,-5.29,-0.12,5.09,2.48,-4.07,-1.37,-1.78,-5.08,-2.05,-6.45,-1.42,1.17
-compallsen		no		no
-debug					0
-dict					/usr/local/lib/python2.7/dist-packages/pocketsphinx/model/cmudict-en-us.dict
-dictcase		no		no
-dither			no		no
-doublebw		no		no
-ds			1		1
-fdict					
-feat			1s_c_d_dd	1s_c_d_dd
-featparams				
-fillprob		1e-8		1.000000e-08
-frate			100		100
-fsg					
-fsgusealtpron		yes		yes
-fsgusefiller		yes		yes
-fwdflat		yes		yes
-fwdflatbeam		1e-64		1.000000e-64
-fwdflatefwid		4		4
-fwdflatlw		8.5		8.500000e+00
-fwdflatsfwin		25		25
-fwdflatwbeam		7e-29		7.000000e-29
-fwdtree		yes		yes
-hmm					/usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us
-input_endian		little		little
-jsgf					
-keyphrase				alexa
-kws					
-kws_delay		10		10
-kws_plp		1e-1		1.000000e-01
-kws_threshold		1		1.000000e-10
-latsize		5000		5000
-lda					
-ldadim			0		0
-lifter			0		22
-lm					
-lmctl					
-lmname					
-logbase		1.0001		1.000100e+00
-logfn					
-logspec		no		no
-lowerf			133.33334	1.300000e+02
-lpbeam			1e-40		1.000000e-40
-lponlybeam		7e-29		7.000000e-29
-lw			6.5		6.500000e+00
-maxhmmpf		30000		30000
-maxwpf			-1		-1
-mdef					
-mean					
-mfclogdir				
-min_endfr		0		0
-mixw					
-mixwfloor		0.0000001	1.000000e-07
-mllr					
-mmap			yes		yes
-ncep			13		13
-nfft			512		512
-nfilt			40		25
-nwpen			1.0		1.000000e+00
-pbeam			1e-48		1.000000e-48
-pip			1.0		1.000000e+00
-pl_beam		1e-10		1.000000e-10
-pl_pbeam		1e-10		1.000000e-10
-pl_pip			1.0		1.000000e+00
-pl_weight		3.0		3.000000e+00
-pl_window		5		5
-rawlogdir				
-remove_dc		no		no
-remove_noise		yes		yes
-remove_silence		yes		yes
-round_filters		yes		yes
-samprate		16000		1.600000e+04
-seed			-1		-1
-sendump				
-senlogdir				
-senmgau				
-silprob		0.005		5.000000e-03
-smoothspec		no		no
-svspec					0-12/13-25/26-38
-tmat					
-tmatfloor		0.0001		1.000000e-04
-topn			4		4
-topn_beam		0		0
-toprule				
-transform		legacy		dct
-unit_area		yes		yes
-upperf			6855.4976	6.800000e+03
-uw			1.0		1.000000e+00
-vad_postspeech		50		50
-vad_prespeech		20		20
-vad_startspeech	10		10
-vad_threshold		2.0		2.000000e+00
-var					
-varfloor		0.0001		1.000000e-04
-varnorm		no		no
-verbose		no		no
-warp_params				
-warp_type		inverse_linear	inverse_linear
-wbeam			7e-29		7.000000e-29
-wip			0.65		6.500000e-01
-wlen			0.025625	2.562500e-02

INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='batch', VARNORM='no', AGC='none'
INFO: acmod.c(166): Using subvector specification 0-12/13-25/26-38
INFO: mdef.c(518): Reading model definition: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/mdef
INFO: mdef.c(531): Found byte-order mark BMDF, assuming this is a binary mdef file
INFO: bin_mdef.c(336): Reading binary model definition: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/mdef
INFO: bin_mdef.c(516): 42 CI-phone, 137053 CD-phone, 3 emitstate/phone, 126 CI-sen, 5126 Sen, 29324 Sen-Seq
INFO: tmat.c(149): Reading HMM transition probability matrices: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/transition_matrices
INFO: acmod.c(117): Attempting to use PTM computation module
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/means
INFO: ms_gauden.c(242): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/variances
INFO: ms_gauden.c(242): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(304): 222 variance values floored
INFO: ptm_mgau.c(476): Loading senones from dump file /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/sendump
INFO: ptm_mgau.c(500): BEGIN FILE FORMAT DESCRIPTION
INFO: ptm_mgau.c(563): Rows: 128, Columns: 5126
INFO: ptm_mgau.c(595): Using memory-mapped I/O for senones
INFO: ptm_mgau.c(838): Maximum top-N: 4
INFO: phone_loop_search.c(114): State beam -225 Phone exit beam -225 Insertion penalty 0
INFO: dict.c(320): Allocating 138824 * 20 bytes (2711 KiB) for word entries
INFO: dict.c(333): Reading main dictionary: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/cmudict-en-us.dict
INFO: dict.c(213): Dictionary size 134723, allocated 1016 KiB for strings, 1679 KiB for phones
INFO: dict.c(336): 134723 words read
INFO: dict.c(358): Reading filler dictionary: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/noisedict
INFO: dict.c(213): Dictionary size 134728, allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(361): 5 words read
INFO: dict2pid.c(396): Building PID tables for dictionary
INFO: dict2pid.c(406): Allocating 42^3 * 2 bytes (144 KiB) for word-initial triphones
INFO: dict2pid.c(132): Allocated 21336 bytes (20 KiB) for word-final triphones
INFO: dict2pid.c(196): Allocated 21336 bytes (20 KiB) for single-phone word triphones
INFO: kws_search.c(406): KWS(beam: -1080, plp: -23, default threshold -225, delay 10)
2017-06-03 16:37:17 DEBUG: Setting up playback handler: VlcHandler
2017-06-03 16:37:24 INFO: Checking Internet Connection ...
2017-06-03 16:37:24 DEBUG: Starting new HTTPS connection (1): api.amazon.com
2017-06-03 16:37:25 DEBUG: https://api.amazon.com:443 "GET /auth/o2/token HTTP/1.1" 404 29
2017-06-03 16:37:25 INFO: Connection OK
2017-06-03 16:37:25 INFO: AVS token: Requesting a new one
2017-06-03 16:37:25 DEBUG: Starting new HTTPS connection (1): api.amazon.com
2017-06-03 16:37:26 DEBUG: https://api.amazon.com:443 "POST /auth/o2/token HTTP/1.1" 200 975
2017-06-03 16:37:27 INFO: AVS token: Obtained successfully
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

2017-06-03 16:37:27 DEBUG: Stopping audio play
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/AlexaPi/src/alexapi/triggers/pocketsphinxtrigger.py", line 55, in thread
    inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL, self._config['sound']['input_device'])
ALSAAudioError: Connection refused [pulse]
2017-06-03 16:37:27 DEBUG: Playing audio: /opt/AlexaPi/src/resources/hello.mp3

2017-06-03 16:37:27 DEBUG: Player State: State.Opening
2017-06-03 16:37:28 DEBUG: Player State: State.Playing
2017-06-03 16:37:28 DEBUG: Started play. 
2017-06-03 16:37:31 DEBUG: Player State: State.Ended
2017-06-03 16:37:31 DEBUG: Finished play.

**Comment by maso27** [comment]
I can't really do much debugging right now, but it looks like PulseAudio isn't cooperating.

You could try changing your input_device from "pulse" to "plughw:CARD=Device,DEV=0".  That's effective on systems that aren't running PulseAudio.

@EmerickH probably has more knowledge than myself.  PA has been a bit messy.

If you want the system to work more smoothly, I'd always recommend installing Jessie Lite instead of the full version.  No PA to fight with.

**Comment by DigZworld** [comment]
I put the output_device: "" in the correct place in the below:
sudo nano /etc/opt/AlexaPi/config.yaml 
in this file, in the sound section, set

input_device: "pulse"
output: "pulse"
output_device: ""

Now I have the following:
pi@raspberrypi:~ $ sudo nano /etc/opt/AlexaPi/config.yaml
pi@raspberrypi:~ $ sudo systemctl stop AlexaPi.service -l
pi@raspberrypi:~ $ sudo systemctl start AlexaPi.service -l
pi@raspberrypi:~ $ sudo systemctl status AlexaPi.service -l
● AlexaPi.service - Alexa client for all your devices
   Loaded: loaded (/usr/lib/systemd/system/AlexaPi.service; enabled)
   Active: active (running) since Sat 2017-06-03 17:00:26 UTC; 9s ago
     Docs: https://github.com/alexa-pi/AlexaPi/wiki
 Main PID: 1846 (python)
   CGroup: /system.slice/AlexaPi.service
           ├─1846 /usr/bin/python /opt/AlexaPi/src/main.py --daemon
           └─1862 /usr/bin/pulseaudio --start --log-target=syslog

Jun 03 17:00:26 raspberrypi systemd[1]: Started Alexa client for all your devices.
Jun 03 17:00:35 raspberrypi pulseaudio[1862]: [pulseaudio] server-lookup.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Jun 03 17:00:35 raspberrypi pulseaudio[1862]: [pulseaudio] main.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Jun 03 17:00:35 raspberrypi pulseaudio[1862]: [pulseaudio] bluez4-util.c: org.bluez.Manager.GetProperties() failed: org.freedesktop.DBus.Error.UnknownMethod: Method "GetProperties" with signature "" on interface "org.bluez.Manager" doesn't exist
pi@raspberrypi:~ $

**Comment by DigZworld** [comment]
Made recommended change: 
try changing your input_device from "pulse" to "plughw:CARD=Device,DEV=0".
And got the following:
pi@raspberrypi:~ $ sudo nano /etc/opt/AlexaPi/config.yaml
pi@raspberrypi:~ $ sudo systemctl stop AlexaPi.service -l
pi@raspberrypi:~ $ sudo systemctl start AlexaPi.service -l
pi@raspberrypi:~ $ sudo systemctl status AlexaPi.service -l
● AlexaPi.service - Alexa client for all your devices
   Loaded: loaded (/usr/lib/systemd/system/AlexaPi.service; enabled)
   Active: active (running) since Sat 2017-06-03 17:07:31 UTC; 14s ago
     Docs: https://github.com/alexa-pi/AlexaPi/wiki
 Main PID: 1940 (python)
   CGroup: /system.slice/AlexaPi.service
           ├─1940 /usr/bin/python /opt/AlexaPi/src/main.py --daemon
           └─1956 /usr/bin/pulseaudio --start --log-target=syslog

Jun 03 17:07:31 raspberrypi systemd[1]: Started Alexa client for all your devices.
Jun 03 17:07:40 raspberrypi pulseaudio[1956]: [pulseaudio] server-lookup.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Jun 03 17:07:40 raspberrypi pulseaudio[1956]: [pulseaudio] main.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Jun 03 17:07:40 raspberrypi pulseaudio[1956]: [pulseaudio] bluez4-util.c: org.bluez.Manager.GetProperties() failed: org.freedesktop.DBus.Error.UnknownMethod: Method "GetProperties" with signature "" on interface "org.bluez.Manager" doesn't exist
pi@raspberrypi:~ $ sudo systemctl status AlexaPi.service -l
● AlexaPi.service - Alexa client for all your devices
   Loaded: loaded (/usr/lib/systemd/system/AlexaPi.service; enabled)
   Active: active (running) since Sat 2017-06-03 17:07:31 UTC; 28s ago
     Docs: https://github.com/alexa-pi/AlexaPi/wiki
 Main PID: 1940 (python)
   CGroup: /system.slice/AlexaPi.service
           ├─1940 /usr/bin/python /opt/AlexaPi/src/main.py --daemon
           └─1956 /usr/bin/pulseaudio --start --log-target=syslog

Jun 03 17:07:31 raspberrypi systemd[1]: Started Alexa client for all your devices.
Jun 03 17:07:40 raspberrypi pulseaudio[1956]: [pulseaudio] server-lookup.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Jun 03 17:07:40 raspberrypi pulseaudio[1956]: [pulseaudio] main.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Jun 03 17:07:40 raspberrypi pulseaudio[1956]: [pulseaudio] bluez4-util.c: org.bluez.Manager.GetProperties() failed: org.freedesktop.DBus.Error.UnknownMethod: Method "GetProperties" with signature "" on interface "org.bluez.Manager" doesn't exist
Jun 03 17:07:47 raspberrypi python[1940]: INFO: Checking Internet Connection ...
Jun 03 17:07:47 raspberrypi python[1940]: INFO: Connection OK
Jun 03 17:07:47 raspberrypi python[1940]: INFO: AVS token: Requesting a new one
Jun 03 17:07:48 raspberrypi python[1940]: INFO: AVS token: Obtained successfully
Jun 03 17:07:51 raspberrypi python[1940]: [0240fb88] alsa audio output error: cannot estimate delay: Input/output error
pi@raspberrypi:~ $ 
Hello Audio is clear.  Any help is greatly appreciated.

Thanks

**Comment by EmerickH** [comment]
Hello,
It's very strange, pulse is searching for a graphical interface!
Try to reinstall all audio system:
```
sudo apt-get remove --purge pulseaudio* alsa*
sudo reboot
sudo apt-get install alsa-utils
sudo apt-get install pulseaudio
sudo reboot
```
Are you using VLC or SOX in your config file?
(playback_handler option I think or someting like this) 

Emerick

**Comment by EmerickH** [comment]
@DigZworld have you tried to reinstall audio?

**Comment by renekliment** [comment]
Closing due to inactivity.
