### ISSUE TITLE
pocketsphinxtrigger error

### ISSUE THREAD

**Issue by ezar** [alexa-pi/AlexaPi#257]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/opt/AlexaPi/src/alexapi/triggers/pocketsphinxtrigger.py", line 73, in thread
  File "/usr/local/lib/python2.7/dist-packages/pocketsphinx/pocketsphinx.py", line 285, in process_raw
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Decoder_process_raw'

**Comment by EmerickH** [comment]
Hello,

> Thank you for reporting an issue with **AlexaPi**.
> 
> In order to help troubleshooting, be sure to include the following information:
> 
> * **Output of the [audio debugging script](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#audio-debugging-script).**
> 
> * **Your OS (including version) where you are running AlexaPi**
> 
> * **Your hardware platform and model you are running on**
> 
> * **Python release (`python2 --version`)**
>
> * **Your `config.yaml` (be sure to remove your Amazon keys)**
>
> * **Steps to reproduce**
> 
Thank you,
Emerick

**Comment by ezar** [comment]
**Output of the [audio debugging script](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#audio-debugging-script).**

http://www.alsa-project.org/db/?f=c06c9e25569d46621bb6cb0c92c08edf318ea32c

**Your OS (including version) where you are running AlexaPi:**
```
Raspbian Jessie Lite
```

**Your hardware platform and model you are running on:**
```
Raspberry 2
```

**Python release (`python2 --version`):**
```
Python 2.7.9
```

**Comment by EmerickH** [comment]
Hello,
this seems to be a pocketsphinx problem, not AlexaPi
Try:
```
pip install --upgrade pip setuptools wheel
pip install --upgrade pocketsphinx
 ```

If it's not working, try to update to python3:
```
sudo apt-get remove --purge python*
sudo apt-get install python3
```
And relaunch the AlexaPi install script

Emerick

**Comment by renekliment** [comment]
Don't purge python2 as they can co-exist and python2 might be a requirement for some system packages.

**Comment by ezar** [comment]
2017-06-13 21:41:38 DEBUG: Initialising Magic Mirror platorm
INFO: pocketsphinx.c(152): Parsed model-specific feature parameters from /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/feat.params
Current configuration:
[NAME]                  [DEFLT]         [VALUE]
-agc                    none            none
-agcthresh              2.0             2.000000e+00
-allphone                               
-allphone_ci            no              no
-alpha                  0.97            9.700000e-01
-ascale                 20.0            2.000000e+01
-aw                     1               1
-backtrace              no              no
-beam                   1e-48           1.000000e-48
-bestpath               yes             yes
-bestpathlw             9.5             9.500000e+00
-ceplen                 13              13
-cmn                    live            batch
-cmninit                40,3,-1         41.00,-5.29,-0.12,5.09,2.48,-4.07,-1.37,-1.78,-5.08,-2.05,-6.45,-1.42,1.17-compallsen             no              no
-debug                                  0
-dict                                   /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/cmudict-en-us.dict
-dictcase               no              no
-dither                 no              no
-doublebw               no              no
-ds                     1               1
-fdict                                  
-feat                   1s_c_d_dd       1s_c_d_dd
-featparams                             
-fillprob               1e-8            1.000000e-08
-frate                  100             100
-fsg                                    
-fsgusealtpron          yes             yes
-fsgusefiller           yes             yes
-fwdflat                yes             yes
-fwdflatbeam            1e-64           1.000000e-64
-fwdflatefwid           4               4
-fwdflatlw              8.5             8.500000e+00
-fwdflatsfwin           25              25
-fwdflatwbeam           7e-29           7.000000e-29
-fwdtree                yes             yes
-hmm                                    /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us
-input_endian           little          little
-jsgf                                   
-keyphrase                              alexa
-kws                                    
-kws_delay              10              10
-kws_plp                1e-1            1.000000e-01
-kws_threshold          1               1.000000e-10
-latsize                5000            5000
-lda                                    
-ldadim                 0               0
-lifter                 0               22
-lm                                     
-lmctl                                  
-lmname                                 
-logbase                1.0001          1.000100e+00
-logfn                                  
-logspec                no              no
-lowerf                 133.33334       1.300000e+02
-lpbeam                 1e-40           1.000000e-40
-lponlybeam             7e-29           7.000000e-29
-lw                     6.5             6.500000e+00
-maxhmmpf               30000           30000
-maxwpf                 -1              -1
-mdef                                   
-mean                                   
-mfclogdir                              
-min_endfr              0               0
-mixw                                   
-mixwfloor              0.0000001       1.000000e-07
-mllr                                   
-mmap                   yes             yes
-ncep                   13              13
-nfft                   512             512
-nfilt                  40              25
-nwpen                  1.0             1.000000e+00
-pbeam                  1e-48           1.000000e-48
-pip                    1.0             1.000000e+00
-pl_beam                1e-10           1.000000e-10
-pl_pbeam               1e-10           1.000000e-10
-pl_pip                 1.0             1.000000e+00
-pl_weight              3.0             3.000000e+00
-pl_window              5               5
-rawlogdir                              
-remove_dc              no              no
-remove_noise           yes             yes
-remove_silence         yes             yes
-round_filters          yes             yes
-samprate               16000           1.600000e+04
-seed                   -1              -1
-sendump                                
-senlogdir                              
-senmgau                                
-silprob                0.005           5.000000e-03
-smoothspec             no              no
-svspec                                 0-12/13-25/26-38
-tmat                                   
-tmatfloor              0.0001          1.000000e-04
-topn                   4               4
-topn_beam              0               0
-toprule                                
-transform              legacy          dct
-unit_area              yes             yes
-upperf                 6855.4976       6.800000e+03
-uw                     1.0             1.000000e+00
-vad_postspeech         50              50
-vad_prespeech          20              20
-vad_startspeech        10              10
-vad_threshold          2.0             2.000000e+00
-var                                    
-varfloor               0.0001          1.000000e-04
-varnorm                no              no
-verbose                no              no
-warp_params                            
-warp_type              inverse_linear  inverse_linear
-wbeam                  7e-29           7.000000e-29
-wip                    0.65            6.500000e-01
-wlen                   0.025625        2.562500e-02

INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='batch', VARNORM='no', AGC='none'
INFO: acmod.c(166): Using subvector specification 0-12/13-25/26-38
INFO: mdef.c(518): Reading model definition: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/mdef
INFO: mdef.c(531): Found byte-order mark BMDF, assuming this is a binary mdef file
INFO: bin_mdef.c(336): Reading binary model definition: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/mdef
INFO: bin_mdef.c(516): 42 CI-phone, 137053 CD-phone, 3 emitstate/phone, 126 CI-sen, 5126 Sen, 29324 Sen-Seq
INFO: tmat.c(149): Reading HMM transition probability matrices: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/transition_matrices
INFO: acmod.c(117): Attempting to use PTM computation module
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/means
INFO: ms_gauden.c(242): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/variances
INFO: ms_gauden.c(242): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(304): 222 variance values floored
INFO: ptm_mgau.c(476): Loading senones from dump file /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/sendump
INFO: ptm_mgau.c(500): BEGIN FILE FORMAT DESCRIPTION
INFO: ptm_mgau.c(563): Rows: 128, Columns: 5126
INFO: ptm_mgau.c(595): Using memory-mapped I/O for senones
INFO: ptm_mgau.c(838): Maximum top-N: 4
INFO: phone_loop_search.c(114): State beam -225 Phone exit beam -225 Insertion penalty 0
INFO: dict.c(320): Allocating 138824 * 20 bytes (2711 KiB) for word entries
INFO: dict.c(333): Reading main dictionary: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/cmudict-en-us.dict
INFO: dict.c(213): Dictionary size 134723, allocated 1016 KiB for strings, 1679 KiB for phones
INFO: dict.c(336): 134723 words read
INFO: dict.c(358): Reading filler dictionary: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/noisedict
INFO: dict.c(213): Dictionary size 134728, allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(361): 5 words read
INFO: dict2pid.c(396): Building PID tables for dictionaryINFO: dict2pid.c(406): Allocating 42^3 * 2 bytes (144 KiB) for word-initial triphones
INFO: dict2pid.c(132): Allocated 21336 bytes (20 KiB) for word-final triphones
INFO: dict2pid.c(196): Allocated 21336 bytes (20 KiB) for single-phone word triphones
INFO: kws_search.c(406): KWS(beam: -1080, plp: -23, default threshold -225, delay 10)
2017-06-13 21:41:40 DEBUG: Setting up playback handler: SoxHandler
2017-06-13 21:41:40 DEBUG: Setting up Magic Mirror platform
2017-06-13 21:41:40 INFO: Magic Mirror HTTP Server - :5055
2017-06-13 21:41:40 INFO: Checking Internet Connection ...
2017-06-13 21:41:40 DEBUG: Starting new HTTPS connection (1): api.amazon.com
2017-06-13 21:41:41 DEBUG: https://api.amazon.com:443 "GET /auth/o2/token HTTP/1.1" 404 29
2017-06-13 21:41:41 INFO: Connection OK
2017-06-13 21:41:41 INFO: AVS token: Requesting a new one2017-06-13 21:41:41 DEBUG: Starting new HTTPS connection (1): api.amazon.com
2017-06-13 21:41:42 DEBUG: https://api.amazon.com:443 "POST /auth/o2/token HTTP/1.1" 200 977
2017-06-13 21:41:42 INFO: AVS token: Obtained successfully
2017-06-13 21:41:42 DEBUG: Starting Magic Mirror platform HTTP Server
2017-06-13 21:41:42 DEBUG: Starting Magic Mirror heartbeat with 5 second interval
2017-06-13 21:41:42 DEBUG: Sending MM Heatbeat
2017-06-13 21:41:42 DEBUG: Response: {"status":"success"}2017-06-13 21:41:42 DEBUG: Stopping audio play
2017-06-13 21:41:43 DEBUG: Stopped play. No SoX process to stop
2017-06-13 21:41:43 DEBUG: Indicate Stop Playing
2017-06-13 21:41:43 DEBUG: Calling URL: http://localhost:8080/alexapi?action=AVSSTATUS&status=idle
2017-06-13 21:41:43 DEBUG: Response: {"status":"success"}2017-06-13 21:41:43 DEBUG: Playing audio: /opt/AlexaPi/src/resources/hello.mp3
2017-06-13 21:41:43 DEBUG: Started play. sox -q /opt/AlexaPi/src/resources/hello.mp3 -t pulseaudio default vol -6 dB pad 0 0
2017-06-13 21:41:43 DEBUG: Indicate Start Playing
2017-06-13 21:41:43 DEBUG: Calling URL: http://localhost:8080/alexapi?action=AVSSTATUS&status=playback
2017-06-13 21:41:43 DEBUG: Response: {"status":"success"}2017-06-13 21:41:45 DEBUG: Finished play. 
2017-06-13 21:41:45 DEBUG: Indicate Stop Playing
2017-06-13 21:41:45 DEBUG: Calling URL: http://localhost:8080/alexapi?action=AVSSTATUS&status=idle
2017-06-13 21:41:46 DEBUG: Response: {"status":"success"}2017-06-13 21:41:46 DEBUG: Indicating Success
2017-06-13 21:41:46 DEBUG: Calling URL: http://localhost:8080/alexapi?action=AVSSTATUS&status=success
2017-06-13 21:41:46 DEBUG: Response: {"status":"success"}2017-06-13 21:41:47 DEBUG: Sending MM Heatbeat
2017-06-13 21:41:47 DEBUG: Response: {"status":"success"}^C2017-06-13 21:41:48 DEBUG: Cleaning up Magic Mirror platform
2017-06-13 21:41:48 DEBUG: Cleaning up playback handler
2017-06-13 21:41:48 DEBUG: Stopped play. [Errno 3] No such process
2017-06-13 21:41:48 DEBUG: Indicate Stop Playing
2017-06-13 21:41:48 DEBUG: Calling URL: http://localhost:8080/alexapi?action=AVSSTATUS&status=idle
2017-06-13 21:41:49 DEBUG: Response: {"status":"success"}INFO: cmn_live.c(88): Update from < 41.00 -5.29 -0.12  5.09  2.48 -4.07 -1.37 -1.78 -5.08 -2.05 -6.45 -1.42  1.17 >
INFO: cmn_live.c(105): Update to   < 44.82 -11.86 -7.02 -2.72 -7.96  0.93  3.32 -5.41 -9.14  0.32 -1.12 -0.98  2.14 >

**Comment by EmerickH** [comment]
Same thing: https://github.com/alexa-pi/AlexaPi/issues/242#issuecomment-308348936

**Comment by renekliment** [comment]
Closing due to inactivity. If there is still a problem:
- try latest Raspbian
- try the snowboy trigger (currently a PR)
