### ISSUE TITLE
Alexa says hello and doesn't answer

### ISSUE THREAD

**Issue by best303** [alexa-pi/AlexaPi#388]
!!Linux Distribution
!!------------------

ID_LIKE=debian

!!DMI Information
!!---------------

Manufacturer:      
Product Name:      
Product Version:   
Firmware Version:  

!!Kernel Information
!!------------------

Kernel release:    4.9.80-v7 
Operating System:  GNU/Linux
Architecture:      armv7l
Processor:         unknown
SMP Enabled:       Yes

!!ALSA Version
!!------------

Driver version:     k4.9.80-v7 
Library version:    1.1.3
Utilities version:  1.1.3

!!Loaded ALSA modules
!!-------------------

snd_bcm2835
snd_usb_audio

!!Sound Servers on this system
!!----------------------------

Jack:
      Installed - Yes (/usr/bin/jackd)
      Running - No

!!Soundcards recognised by ALSA
!!-----------------------------

 0 [ALSA           ]: bcm2835 - bcm2835 ALSA
                      bcm2835 ALSA
 1 [Device         ]: USB-Audio - USB PnP Sound Device
                      C-Media Electronics Inc. USB PnP Sound Device at usb-3f980000.usb-1.4, full spe

!!Modprobe options (Sound related)
!!--------------------------------

snd_pcsp: index=-2
snd_usb_audio: index=-2
snd_atiixp_modem: index=-2
snd_intel8x0m: index=-2
snd_via82xx_modem: index=-2

!!Loaded sound module options
!!---------------------------

!!Module: snd_bcm2835
	force_bulk : N

!!Module: snd_usb_audio
	autoclock : Y
	device_setup : 0,0,0,0,0,0,0,0
	enable : Y,Y,Y,Y,Y,Y,Y,Y
	id : (null),(null),(null),(null),(null),(null),(null),(null)
	ignore_ctl_error : N
	index : -2,-1,-1,-1,-1,-1,-1,-1
	pid : -1,-1,-1,-1,-1,-1,-1,-1
	quirk_alias : (null),(null),(null),(null),(null),(null),(null),(null)
	vid : -1,-1,-1,-1,-1,-1,-1,-1

!!USB Mixer information
!!---------------------
--startcollapse--

USB Mixer: usb_id=0x0d8c013c, ctrlif=0, ctlerr=0
Card: C-Media Electronics Inc. USB PnP Sound Device at usb-3f980000.usb-1.4, full spe
  Unit: 10
    Control: name="Auto Gain Control", index=0
    Info: id=10, control=7, cmask=0x0, channels=1, type="BOOLEAN"
    Volume: min=0, max=1, dBmin=0, dBmax=0
  Unit: 10
    Control: name="Mic Capture Volume", index=0
    Info: id=10, control=2, cmask=0x0, channels=1, type="S16"
    Volume: min=0, max=6096, dBmin=0, dBmax=2381
  Unit: 10
    Control: name="Mic Capture Switch", index=0
    Info: id=10, control=1, cmask=0x0, channels=1, type="INV_BOOLEAN"
    Volume: min=0, max=1, dBmin=0, dBmax=0
--endcollapse--

!!ALSA Device nodes
!!-----------------

crw-rw----  1 root audio 116,  0 Mar 24 18:26 /dev/snd/controlC0
crw-rw----  1 root audio 116, 32 Mar 24 18:26 /dev/snd/controlC1
crw-rw----  1 root audio 116, 16 Mar 24 18:27 /dev/snd/pcmC0D0p
crw-rw----  1 root audio 116, 17 Mar 24 18:26 /dev/snd/pcmC0D1p
crw-rw----  1 root audio 116, 56 Mar 24 18:26 /dev/snd/pcmC1D0c
crw-rw----  1 root audio 116,  1 Mar 24 18:26 /dev/snd/seq
crw-rw----  1 root audio 116, 33 Mar 24 18:26 /dev/snd/timer

/dev/snd/by-id:
total 0
drwxr-xr-x 2 root root  60 Mar 24 18:26 .
drwxr-xr-x 4 root root 220 Mar 24 18:26 ..
lrwxrwxrwx 1 root root  12 Mar 24 18:26 usb-C-Media_Electronics_Inc._USB_PnP_Sound_Device-00 -> ../controlC1

/dev/snd/by-path:
total 0
drwxr-xr-x 2 root root  80 Mar 24 18:26 .
drwxr-xr-x 4 root root 220 Mar 24 18:26 ..
lrwxrwxrwx 1 root root  12 Mar 24 18:26 platform-3f980000.usb-usb-0:1.4:1.0 -> ../controlC1
lrwxrwxrwx 1 root root  12 Mar 24 18:26 platform-soc:audio -> ../controlC0

!!Aplay/Arecord output
!!--------------------

APLAY

**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

ARECORD

**** List of CAPTURE Hardware Devices ****
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

!!Amixer output
!!-------------

!!-------Mixer controls for card 0 [ALSA]

Card hw:0 'ALSA'/'bcm2835 ALSA'
  Mixer name	: 'Broadcom Mixer'
  Components	: ''
  Controls      : 6
  Simple ctrls  : 1
Simple mixer control 'PCM',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback -10239 - 400
  Mono: Playback -638 [90%] [-6.38dB] [on]

!!-------Mixer controls for card 1 [Device]

Card hw:1 'Device'/'C-Media Electronics Inc. USB PnP Sound Device at usb-3f980000.usb-1.4, full spe'
  Mixer name	: 'USB Mixer'
  Components	: 'USB0d8c:013c'
  Controls      : 4
  Simple ctrls  : 2
Simple mixer control 'Mic',0
  Capabilities: cvolume cvolume-joined cswitch cswitch-joined
  Capture channels: Mono
  Limits: Capture 0 - 16
  Mono: Capture 14 [88%] [20.83dB] [on]
Simple mixer control 'Auto Gain Control',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]

!!Alsactl output
!!--------------

--startcollapse--
state.ALSA {
	control.1 {
		iface MIXER
		name 'PCM Playback Volume'
		value -638
		comment {
			access 'read write'
			type INTEGER
			count 1
			range '-10239 - 400'
			dbmin -9999999
			dbmax 400
			dbvalue.0 -638
		}
	}
	control.2 {
		iface MIXER
		name 'PCM Playback Switch'
		value true
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.3 {
		iface MIXER
		name 'PCM Playback Route'
		value 1
		comment {
			access 'read write'
			type INTEGER
			count 1
			range '0 - 2'
		}
	}
	control.4 {
		iface PCM
		name 'IEC958 Playback Default'
		value '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access 'read write'
			type IEC958
			count 1
		}
	}
	control.5 {
		iface PCM
		name 'IEC958 Playback Con Mask'
		value '0200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access read
			type IEC958
			count 1
		}
	}
	control.6 {
		iface PCM
		name 'IEC958 Playback PCM Stream'
		value '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
		comment {
			access 'read write inactive'
			type IEC958
			count 1
		}
	}
}
state.Device {
	control.1 {
		iface PCM
		name 'Capture Channel Map'
		value 2
		comment {
			access read
			type INTEGER
			count 1
			range '0 - 36'
		}
	}
	control.2 {
		iface MIXER
		name 'Mic Capture Switch'
		value true
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
	control.3 {
		iface MIXER
		name 'Mic Capture Volume'
		value 14
		comment {
			access 'read write'
			type INTEGER
			count 1
			range '0 - 16'
			dbmin 0
			dbmax 2381
			dbvalue.0 2083
		}
	}
	control.4 {
		iface MIXER
		name 'Auto Gain Control'
		value true
		comment {
			access 'read write'
			type BOOLEAN
			count 1
		}
	}
}
--endcollapse--

!!All Loaded Modules
!!------------------

Module
fuse
rfcomm
cmac
bnep
hci_uart
btbcm
bluetooth
spidev
brcmfmac
brcmutil
cfg80211
rfkill
snd_bcm2835
i2c_bcm2835
spi_bcm2835
bcm2835_gpiomem
w1_gpio
wire
joydev
evdev
cn
uio_pdrv_genirq
uio
fixed
snd_usb_audio
snd_hwdep
snd_usbmidi_lib
snd_rawmidi
snd_seq_device
snd_pcm
snd_timer
snd
i2c_dev
ip_tables
x_tables
ipv6

!!ALSA/HDA dmesg
!!--------------

[    2.825503] systemd-journald[118]: Received request to flush runtime journal from PID 1
[    3.274159] usbcore: registered new interface driver snd-usb-audio
[    3.300661] Driver for 1-wire Dallas network protocol.
**Description of problem:**
My usb mic won't work, infact when I try the record test,
#(arecord -f S16_LE -r 16000 -D your_input_device test.wav)
I get: 
"ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM your_input_device
arecord: main:788: audio open error: No such file or directory"

Furthermore I get a lot of ALSA errors when I check for the AlexaPi status:

Mar 24 18:27:20 raspberrypi python[456]: ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
Mar 24 18:27:20 raspberrypi python[456]: ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
Mar 24 18:27:20 raspberrypi python[456]: connect(2) call to /tmp/jack-999/default/jack_0 failed (err=No such file or directory)
Mar 24 18:27:20 raspberrypi python[456]: attempt to connect to server failed
Mar 24 18:27:23 raspberrypi python[456]: INFO: Checking Internet Connection ...
Mar 24 18:27:24 raspberrypi python[456]: INFO: Connection OK
Mar 24 18:27:24 raspberrypi python[456]: INFO: AVS token: Requesting a new one
Mar 24 18:27:24 raspberrypi python[456]: INFO: AVS token: Obtained successfully
Mar 24 18:27:27 raspberrypi python[456]: [02c2dad0] core input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 300 ms)
Mar 24 18:27:27 raspberrypi python[456]: [02c2dad0] core input error: ES_OUT_RESET_PCR called

**Expected:**
```

```

**Problem-relevant `config.yaml` entries:**
```

```

**Steps to reproduce:**

1. 
2. 
3. 

**Traceback (if applicable):**
```

```

**Additional info:**
```

```

**Comment by best303** [comment]
I tried with another command: 

/opt/AlexaPi/src/main.py 


and result is.

ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
2018-03-24 20:52:19 INFO: Checking Internet Connection ...
2018-03-24 20:52:20 INFO: Connection OK
2018-03-24 20:52:20 INFO: AVS token: Requesting a new one
2018-03-24 20:52:20 INFO: AVS token: Obtained successfully
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/AlexaPi/src/alexapi/triggers/pocketsphinxtrigger.py", line 66, in thread
    self._capture.handle_init(self.AUDIO_RATE, self.AUDIO_CHUNK_SIZE)
  File "/opt/AlexaPi/src/alexapi/capture.py", line 113, in handle_init
    frames_per_buffer=chunk_size
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9996] Invalid input device (no default output device)

**Comment by WeirdlyChosen** [comment]
I too have this problem. 
Expected:
AlexaPi says hello, then responding to my voice

Problem-relevant config.yaml entries:
input_device: ""
output: ""
output device: "magicmirror" //this is default from installation
output_device: "default"

Steps to reproduce:
1. Install AlexaPi
2. set up system wide pulse audio using this [guide](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#pulseaudio)
3. AlexaPi failed to start after reboot
4. change config.yaml to be written above
Traceback (if applicable):


Additional info:
Installed magicmirror before installing AlexaPi
AlexaPi working normally after installing and starting manually
does not stop AlexaPi while Changing to system wide PulseAudio

**Comment by EmerickH** [comment]
@WeirdlyChosen I don't know how works MM but I think you also have to setup your audio devices.

@best303 you have to setup your audio PCMs:
List them with `aplay -L` and change it in the config:
```
output: "alsa"
output_device: "plughw:YOURDEVICE"
```

**Comment by ZmeiGorynych** [comment]
@EmerickH Thanks! Just ran into the same issue - which config is it that I should change?

**Comment by jacobkaufman** [comment]
You can set your alsa devices in `/etc/asound.conf` for system-wide or `~/.asoundrc` for individual user. If the file doesn't exist you have to create it. If you have a separate mic and speaker then they will be different cards. On the Raspberry Pi my Speaker Bonnet is card0 and my USB mic is card1.
