### ISSUE TITLE
"ImportError: No Module named queue"

### ISSUE THREAD

**Issue by Dasbomber** [alexa-pi/AlexaPi#425]
Couple days ago I saw that you could make your own Alexa device using a raspberry pi and I thought it would be a fun experiment building my own alexa device. As expected I've ran into a lot of errors and such but after a few hours in total of googling I've managed to find solutions to each error I've encountered until now. This is what it says: 

● AlexaPi.service - Alexa client for all your devices
   Loaded: loaded (/usr/lib/systemd/system/AlexaPi.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-10-31 15:02:44 CET; 1min 23s ago
     Docs: https://github.com/alexa-pi/AlexaPi/wiki
  Process: 416 ExecStart=/usr/bin/python /opt/AlexaPi/src/main.py --daemon (code=exited, status=1/FAILURE)
 Main PID: 416 (code=exited, status=1/FAILURE)

okt 31 15:02:38 raspberrypi systemd[1]: Started Alexa client for all your devices.
okt 31 15:02:43 raspberrypi python[416]: Traceback (most recent call last):
okt 31 15:02:43 raspberrypi python[416]:   File "/opt/AlexaPi/src/main.py", line 25, in <module>
okt 31 15:02:43 raspberrypi python[416]:     import alexapi.capture
okt 31 15:02:43 raspberrypi python[416]:   File "/opt/AlexaPi/src/alexapi/capture.py", line 5, in <module>
okt 31 15:02:43 raspberrypi python[416]:     import queue
okt 31 15:02:43 raspberrypi python[416]: ImportError: No module named queue
okt 31 15:02:44 raspberrypi systemd[1]: AlexaPi.service: Main process exited, code=exited, status=1/FAILURE
okt 31 15:02:44 raspberrypi systemd[1]: AlexaPi.service: Unit entered failed state.
okt 31 15:02:44 raspberrypi systemd[1]: AlexaPi.service: Failed with result 'exit-code'.

I've tried searching for errors like this one but from my searching, I didn't manage to find anything that looked like my error. I've tried to unistall AlexaPi and then install it again but it didn't work. The authorization progress worked great so that shouldn't be the problem.

**Comment by Dasbomber** [comment]
I changed "import queue" to "import Queue" with a big Q within /opt/AlexaPi/src/alexapi/capture.py

The reason behind depends on what version if python that is used. If you have the same problem, try changing the "queue/Queue" into the opposite.
